### ISSUE TITLE
Spelling and Grammatical errors

### ISSUE THREAD

**Issue by Davidkeebler** [learn-co-curriculum/dsc-applying-gradient-descent-lab#2]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x ] Instructions unclear
- [x ] Other (explain below)

### Source

```

```

### Concern

The text of this jupyter notebook contains many spelling and grammatical errors that make it difficult to understand and learn from.

## What OS Are You Using?

- [ ] OS X
- [x ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Taking a look. Thank you for raising this issue.

**Comment by bpurdy-ds** [comment]
Checked for spelling error, and fixed readability issues. Thanks again for the comment.
